services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    platform: linux/amd64
    container_name: sql2025
    hostname: sql2025

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"

    ports:
      - "1433:1433"

    volumes:
      - sql2025-data:/var/opt/mssql

volumes:
  sql2025-data:
